### ISSUE TITLE
Remora default model warning [Bonito]

### ISSUE THREAD

**Issue by esteinig** [nanoporetech/remora#7] opened 2022-01-25 21:40 UTC
Hi Marcus and team, thanks for working on the methylation calling and integration with Bonito.

I thought to open an issue here because we consistently get a Remora warning (regardless of Bonito installation on multiple systems / containers) that the version of the model is not available and the default model is used instead, e.g.

```
bonito basecaller dna_r9.4.1_e8.1_fast@v3.4 --modified-bases 5mC  --reference chm13.mmi fast5/ > basecalls.bam
> loading model dna_r9.4.1_e8.1_fast@v3.4
> loading modified base model
> warning (remora): Remora model for basecall model version (v3.4) not found. Using default Remora model for dna_r9.4.1_e8.1_fast.
> loaded modified base model to call (alt to C): m=5mC
> loading reference
> outputting aligned bam
...
```

My question is whether this is intended behaviour? It seems like that no other models but the default models are available when checking with Remora:

```
remora model list_pretrained

[07:33:21] Remora pretrained modified base models:
Pore             Basecall_Model_Type    Basecall_Model_Version    Modified_Bases    Remora_Model_Type      Remora_Model_Version
---------------  ---------------------  ------------------------  ----------------  -------------------  ----------------------
dna_r9.4.1_e8    fast                   0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8    fast                   0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8    hac                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8    hac                    0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8    sup                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8    sup                    0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8.1  fast                   0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8.1  hac                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8.1  sup                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   fast                   0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   fast                   0.0.0                     5hmc_5mc          CG                                        0
dna_r10.4_e8.1   hac                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   hac                    0.0.0                     5hmc_5mc          CG                                        0
dna_r10.4_e8.1   sup                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   sup                    0.0.0                     5hmc_5mc          CG                                        0
```

**Comment by cjw85** [comment] 2022-01-26 09:24
Hi Eike,

This is the currently intended behaviour. We will certainly have updated models released in the coming months.

**Closed by cjw85** 2022-01-26 09:24 UTC

**Comment by esteinig** [comment] 2022-01-26 22:43
Thanks so much @cjw85 - appreciate the quick response!
